const test = require('node:test')
const assert = require('node:assert/strict')
const { readFileSync } = require('node:fs')
const path = require('node:path')
const root = path.join(__dirname, '..')

test('broadcast task keeps text and image as separate steps for every selected target', () => {
  const page = readFileSync(path.join(root, 'src', 'pages', 'BroadcastPage.vue'), 'utf8')
  const main = readFileSync(path.join(root, 'electron', 'main.cjs'), 'utf8')

  assert.match(page, /SEND_MIXED_TO_FRIEND/)
  assert.match(page, /actionType: 'SEND_TEXT'/)
  assert.match(page, /actionType: 'SEND_IMAGE'/)
  assert.match(page, /instanceId: String\(target\.sourceInstanceId\)/)
  assert.match(page, /filepath: image/)
  assert.doesNotMatch(page, /v-model="contentType"/)
  assert.doesNotMatch(page, /allocMode|accountWeights|allocationPool/)
  assert.match(main, /item\.action_type === 'SEND_IMAGE'/)
  assert.match(main, /api\/send_image_msg/)
  assert.match(main, /sourceId = 438557485/)
  assert.doesNotMatch(main, /imageTask \? 'BLOCKED_API_UNVERIFIED'/)
})

test('broadcast requires explicit sender WeChat selection and shows account column', () => {
  const page = readFileSync(path.join(root, 'src', 'pages', 'BroadcastPage.vue'), 'utf8')
  assert.match(page, /selectedInstanceIds/)
  assert.match(page, /发送微信号/)
  assert.match(page, /label: '发送微信'/)
  assert.match(page, /rowKey: `\$\{item\.sourceInstanceId\}::\$\{item\.wxid\}`/)
  assert.match(page, /formatAccountSummary/)
  assert.doesNotMatch(page, /轮询分配|按权重分配/)
})

test('broadcast friend list excludes official accounts and supports remark contains filter', () => {
  const page = readFileSync(path.join(root, 'src', 'pages', 'BroadcastPage.vue'), 'utf8')
  assert.match(page, /!isOfficialAccountWxid\(item\.wxid\)/)
  assert.match(page, /excludeRemark/)
  assert.match(page, /remarkMatchesExclude\(item\.remark, remarkRules\)/)
  assert.match(page, /resolveSendableTargets/)
  assert.match(page, /selectAllFilteredTargets/)
  assert.match(page, /VirtualTargetTable/)
})

test('broadcast uses virtual table so select-all covers full filtered list without mounting all rows', () => {
  const page = readFileSync(path.join(root, 'src', 'pages', 'BroadcastPage.vue'), 'utf8')
  const virt = readFileSync(path.join(root, 'src', 'components', 'app', 'VirtualTargetTable.vue'), 'utf8')
  assert.match(page, /selectAllFilteredTargets\(true\)/)
  assert.match(page, /selectedTargets\.value = broadcastFriends\.value\.slice\(\)/)
  assert.doesNotMatch(page, /<el-table[\s>]/)
  assert.match(virt, /visibleRows/)
  assert.match(virt, /startIndex/)
  assert.match(virt, /overscan/)
  assert.match(virt, /select-all/)
})

test('broadcast accepts clipboard images without triggering a send', () => {
  const page = readFileSync(path.join(root, 'src', 'pages', 'BroadcastPage.vue'), 'utf8')
  const main = readFileSync(path.join(root, 'electron', 'main.cjs'), 'utf8')
  const preload = readFileSync(path.join(root, 'electron', 'preload.cjs'), 'utf8')
  assert.match(page, /document\.addEventListener\('paste', onPaste\)/)
  assert.match(page, /item\.type\.startsWith\('image\/'\)/)
  assert.match(page, /window\.wxControl\?\.pasteImage\(\)/)
  assert.match(main, /ipcMain\.handle\('files:paste-image'/)
  assert.match(main, /clipboard\.readImage\(\)/)
  assert.match(main, /writeFileSync\(imagePath, png\)/)
  assert.match(preload, /pasteImage: \(\) => ipcRenderer\.invoke\('files:paste-image'\)/)
})

test('broadcast create path still validates ownership in main process', () => {
  const main = readFileSync(path.join(root, 'electron', 'main.cjs'), 'utf8')
  assert.match(main, /loadDirectoryOwnershipSet/)
  assert.match(main, /ownedKeysOf\(instanceId\)\.has\(targetKey\)/)
  assert.match(main, /SEND_MIXED_TO_FRIEND/)
  assert.match(main, /SEND_MIXED_TO_GROUP/)
  assert.match(main, /item\.action_type === 'SEND_TEXT' \|\| item\.action_type === 'SEND_IMAGE'/)
})

test('broadcast create/run guards friend-group mix and missing image file', () => {
  const page = readFileSync(path.join(root, 'src', 'pages', 'BroadcastPage.vue'), 'utf8')
  const main = readFileSync(path.join(root, 'electron', 'main.cjs'), 'utf8')
  assert.match(page, /!String\(item\.wxid \|\| ''\)\.endsWith\('@chatroom'\)/)
  assert.match(page, /String\(item\.roomId \|\| ''\)\.endsWith\('@chatroom'\)/)
  assert.match(main, /群聊群发只能选择群聊对象/)
  assert.match(main, /好友群发不能选择群聊对象/)
  assert.match(main, /图片文件不存在，请重新选择图片/)
  assert.match(main, /图文混发必须标明每条是文字还是图片/)
  assert.match(main, /wxid: String\(item\.target_key \|\| ''\)/)
  assert.match(main, /deliveryImageHashCache/)
  assert.match(main, /图片文件不存在或已被移动/)
})
