const test = require('node:test')
const assert = require('node:assert/strict')
const { readFileSync } = require('node:fs')
const path = require('node:path')

test('directory refresh is shared, cached, partially tolerant, and logs concrete failures', () => {
  const store = readFileSync(path.join(__dirname, '..', 'src', 'stores', 'wechatData.ts'), 'utf8')
  const preload = readFileSync(path.join(__dirname, '..', 'electron', 'preload.cjs'), 'utf8')
  const main = readFileSync(path.join(__dirname, '..', 'electron', 'main.cjs'), 'utf8')
  assert.match(store, /directoryRefreshPromise/)
  assert.match(store, /Date\.now\(\) - directoryRefreshedAt < 5000/)
  assert.match(store, /刷新通讯录部分失败/)
  assert.match(store, /directorySyncPayload\(\{ contactInstanceIds: refreshedContactInstances, groupInstanceIds: refreshedGroupInstances \}\)/)
  assert.match(store, /memberRooms: \[\{ instanceId: instance\.id, roomId \}\]/)
  assert.doesNotMatch(store, /syncDirectory\?\.\(\{ contacts: contacts\.value/)
  assert.match(preload, /app:report-error/)
  assert.match(preload, /plainIpcValue\(payload\)/)
  assert.match(preload, /plainIpcValue/)
  assert.match(store, /通讯录读取成功，但保存读取结果失败/)
  assert.match(main, /ipcMain\.handle\('app:report-error'/)
  assert.match(main, /safeCloneForIpc\(raw/)
})

test('directory refresh merges chatroom list, room cache, all-room detail and contact groups', () => {
  const store = readFileSync(path.join(__dirname, '..', 'src', 'stores', 'wechatData.ts'), 'utf8')
  const main = readFileSync(path.join(__dirname, '..', 'electron', 'main.cjs'), 'utf8')
  assert.match(store, /function collectChatroomRows/)
  assert.match(store, /function upsertGroupRow/)
  assert.match(store, /\/api\/get_all_room_detail/)
  assert.match(store, /\/api\/batch_getroom_cache/)
  assert.match(store, /\/api\/get_chatroom_list/)
  assert.match(store, /contact\.isGroup/)
  assert.match(store, /cachedGroups/)
  assert.match(main, /\/api\/get_all_room_detail': '读取全量群详情'/)
})
