const test = require('node:test')
const assert = require('node:assert/strict')
const { readFileSync } = require('node:fs')
const path = require('node:path')

test('MeshCentral remote support is wired; legacy WebRTC stack is gone', () => {
  const root = path.join(__dirname, '..')
  const main = readFileSync(path.join(root, 'electron', 'main.cjs'), 'utf8')
  const preload = readFileSync(path.join(root, 'electron', 'preload.cjs'), 'utf8')
  const router = readFileSync(path.join(root, 'src', 'router', 'index.ts'), 'utf8')
  const layout = readFileSync(path.join(root, 'src', 'layout', 'MainLayout.vue'), 'utf8')

  assert.match(main, /startRemoteAgent\(/)
  assert.match(main, /mesh:open-desktop/)
  assert.match(main, /mesh-remote-bridge/)
  assert.doesNotMatch(main, /webrtc-desktop|win-input|desktopCapturer/)
  assert.match(preload, /remoteOpenDesktop|mesh:open-desktop|remoteGetStatus/)
  assert.match(router, /remote-support|RemoteSupport/)
  assert.match(layout, /远程维护/)
  assert.doesNotMatch(layout, /远程桌面|后台地址|云端后台/)
})
