const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const root = path.resolve(__dirname, '..')
const remote = fs.readFileSync(path.join(root, 'electron/remote-agent.cjs'), 'utf8')
const main = fs.readFileSync(path.join(root, 'electron/main.cjs'), 'utf8')

test('remote commands acknowledge only after a supported action is handled', () => {
  assert.match(remote, /status: 'RECEIVED'/)
  assert.match(remote, /status: 'APPLIED'/)
  assert.match(remote, /status: 'FAILED'/)
  assert.match(remote, /type === 'deny_run'/)
  assert.match(remote, /type === 'allow_run'/)
  assert.match(remote, /type === 'announce'/)
  assert.doesNotMatch(remote, /if \(message\?\.commandId \|\| message\?\.id\) send\(\{ type: 'command_ack'.*status: 'APPLIED'/)
  assert.match(main, /requireRuntime\(\)/)
})

test('remote connection has WSS enforcement, liveness checks and frame backpressure', () => {
  assert.match(remote, /公网连接必须使用 WSS/)
  assert.match(remote, /heartbeat_ack/)
  assert.match(remote, /Date\.now\(\) - lastServerAt > 50000/)
  assert.match(remote, /2 \*\* reconnectAttempt/)
  assert.match(remote, /BUFFER_DROP_BYTES/)
  assert.match(remote, /BUFFER_HARD_BYTES/)
  assert.match(remote, /markSendBacklog/)
  assert.match(remote, /CAPTURE_INTERVAL_DRAIN_MS/)
  assert.match(remote, /JPEG_QUALITY_NORMAL/)
  assert.match(remote, /JPEG_QUALITY_LOW/)
})

test('remote desktop prefers LiveKit publish with JPEG snapshot fallback', () => {
  assert.match(remote, /const DESKTOP_CAPTURE_ENABLED = true/)
  assert.match(remote, /const DESKTOP_WEBRTC_ENABLED = true/)
  assert.match(remote, /webrtc: DESKTOP_WEBRTC_ENABLED/)
  assert.match(remote, /startWebRtcFromMessage/)
  assert.match(remote, /JPEG_SNAPSHOT_INTERVAL_MS/)
  const pub = fs.readFileSync(path.join(root, 'electron/webrtc-desktop.cjs'), 'utf8')
  const html = fs.readFileSync(path.join(root, 'electron/webrtc-publisher.html'), 'utf8')
  assert.match(pub, /setDisplayMediaRequestHandler/)
  assert.match(pub, /show: false/)
  assert.match(pub, /livekitUrl/)
  assert.match(html, /livekit-client\.umd\.js/)
  assert.match(html, /LK\.Room/)
  assert.match(html, /webrtc_offer/)
  assert.match(html, /transport: 'livekit'/)
})

test('remote desktop capture composites mouse cursor and prefers smoother pacing', () => {
  assert.match(remote, /function compositeCursor/)
  assert.match(remote, /function paintArrowCursor/)
  assert.match(remote, /function scheduleCapture/)
  assert.match(remote, /function nextCaptureDelay/)
  assert.match(remote, /CAPTURE_MAX_WIDTH = 1280/)
  assert.match(remote, /CAPTURE_MAX_HEIGHT = 720/)
  assert.match(remote, /JPEG_QUALITY_NORMAL = 70/)
  assert.match(remote, /CAPTURE_INTERVAL_FAST_MS = 90/)
  assert.match(remote, /CAPTURE_INTERVAL_MS = 150/)
  assert.match(remote, /cursor: composed\.cursor/)
  assert.match(remote, /getCursorScreenPoint/)
  assert.match(remote, /paintCursor/)
})

test('remote desktop uses dirty-rect deltas like Kaiyun when unchanged tiles skip send', () => {
  assert.match(remote, /function collectDirtyTiles/)
  assert.match(remote, /function dirtyAreaRatio/)
  assert.match(remote, /TILE_SIZE = 64/)
  assert.match(remote, /DELTA_DIRTY_AREA_LIMIT = 0\.35/)
  assert.match(remote, /DELTA_KEYFRAME_EVERY_N = 60/)
  assert.match(remote, /DELTA_KEYFRAME_MAX_AGE_MS = 8000/)
  assert.match(remote, /CAPTURE_INTERVAL_FAST_MS = 90/)
  assert.match(remote, /CAPTURE_INTERVAL_MS = 150/)
  assert.match(remote, /type: 'frame_delta'/)
  assert.match(remote, /desktopDelta: DESKTOP_CAPTURE_ENABLED/)
  assert.match(remote, /画面无变化：不传图/)
  assert.match(remote, /forceRestart/)
  assert.match(remote, /resetDeltaState/)
})

test('desktop client syncs useful WeChat summaries without message bodies', () => {
  const storage = fs.readFileSync(path.join(root, 'electron/storage.cjs'), 'utf8')
  assert.match(remote, /type: 'wx_sync'/)
  assert.match(storage, /remoteSyncSnapshot/)
  assert.match(storage, /instances:/)
  assert.match(storage, /contacts:/)
  assert.match(storage, /groups:/)
  assert.match(storage, /members:/)
  assert.match(storage, /tasks:/)
  assert.match(storage, /taskItems/)
  assert.match(storage, /selectLogsForRemoteSync/)
  assert.match(storage, /logs: diagnostics/)
  assert.match(storage, /businessCode/)
  // 同步快照不得把任务/接口正文字段原样上报（允许内部 SQL 引用列名）
  const syncFn = storage.slice(storage.indexOf('function remoteSyncSnapshot'))
  const syncReturn = syncFn.slice(syncFn.indexOf('return {'), syncFn.indexOf('}\n', syncFn.indexOf('return {')) + 1)
  assert.doesNotMatch(syncReturn, /request_json|response_json/)
})

test('logic bugfixes: packaged hooks, cooling resume, single-instance guard, commandId-only ack', () => {
  assert.match(main, /function resolveHookSourceDir/)
  assert.match(main, /'hook',\s*'4\.1\.8\.27'/)
  assert.match(main, /resources',\s*'hook'/)
  assert.doesNotMatch(main, /E:\\\\我的软件源码/)
  assert.doesNotMatch(main, /LEGACY_WEIXIN_FALLBACK/)
  assert.match(main, /if \(!hasSingleInstanceLock\) return/)
  assert.match(main, /pauseActiveTasks/)
  assert.match(main, /任务因频繁状态冷却中/)
  assert.doesNotMatch(main, /if \(item\.action_type !== 'QR_SCAN'\) return/)
  assert.match(remote, /仅认 commandId/)
  assert.match(remote, /const commandId = message\?\.commandId/)
  const auth = fs.readFileSync(path.join(root, 'electron/software-auth.cjs'), 'utf8')
  assert.match(auth, /网络抖动保留本地登录态/)
  const winInput = fs.readFileSync(path.join(root, 'electron/win-input.cjs'), 'utf8')
  assert.match(winInput, /scaleFactor/)
  const identity = fs.readFileSync(path.join(root, 'electron/device-identity.cjs'), 'utf8')
  assert.match(identity, /if \(!raw\.clientId\)/)
})
