const test = require('node:test')
const assert = require('node:assert/strict')
const { readFileSync } = require('node:fs')
const path = require('node:path')

test('settings tabs display separate groups of settings that are actually used', () => {
  const root = path.join(__dirname, '..')
  const page = readFileSync(path.join(root, 'src', 'pages', 'SettingsLogsPage.vue'), 'utf8')
  const main = readFileSync(path.join(root, 'electron', 'main.cjs'), 'utf8')

  assert.match(page, /\['任务与频率', '连接设置', '文件位置'\]/)
  assert.match(page, /v-if="activeMenu === '任务与频率'"/)
  assert.match(page, /v-else-if="activeMenu === '连接设置'"/)
  assert.match(page, /selectQrDirectory/)
  assert.match(page, /微信安装路径/)
  assert.match(page, /selectWeixinExecutable/)
  assert.match(page, /detectWeixinInstall/)
  assert.match(page, /重新检测/)
  assert.match(page, /创建清理任务/)
  assert.match(page, /cleanupKickedGroups/)
  assert.match(page, /promptGoToTaskCenter/)
  assert.match(main, /kicked-groups:cleanup/)
  assert.match(main, /prepareKickedGroupCleanupTask/)
  assert.match(main, /KICKED_GROUP_CLEANUP/)
  assert.match(main, /files:select-directory/)
  assert.match(main, /files:select-weixin/)
  assert.match(main, /configuredWeixinExe\(\)/)
  assert.match(main, /ensureWeixinPathConfigured/)
  assert.doesNotMatch(main, /const WEIXIN_SOURCE/)
  assert.doesNotMatch(page, /重试策略|最大重试次数|加入群聊每日上限|消息保存目录/)
})
