const test = require('node:test')
const assert = require('node:assert/strict')
const { readFileSync } = require('node:fs')
const path = require('node:path')

const read = (file) => readFileSync(path.join(__dirname, '..', file), 'utf8')

test('QR join uses selected executors × selected groups (not round-robin)', () => {
  const page = read('src/pages/QrTasksPage.vue')
  const main = read('electron/main.cjs')
  assert.match(page, /assignMode/)
  assert.match(page, /selectedExecutorIds/)
  assert.match(page, /plannedPairs/)
  assert.match(page, /plannedTaskCount/)
  assert.match(page, /targetKey = `\$\{instanceId\}::\$\{qrKey\}`/)
  assert.match(page, /sourceLabel/)
  assert.match(page, /executorInstanceId/)
  assert.match(page, /所选微信执行全部已选群/)
  assert.match(page, /手动给群分配执行微信/)
  assert.match(page, /60 个群 ×|个群 × .* 个微信 =/)
  assert.match(page, /创建识别与进群任务 · \{\{ plannedTaskCount \}\}/)
  assert.doesNotMatch(page, /index % availableInstances\.length/)
  assert.doesNotMatch(page, /capacity = availableInstances\.length \* limitPerAccount\.value/)
  assert.match(page, /limitPerAccount:\s*limitPerAccount\.value/)
  assert.match(page, /coolMinutes:\s*coolMinutes\.value/)
  assert.match(page, /applyText:\s*applyText\.value/)
  assert.match(page, /你好，想加入群聊/)
  assert.match(page, /skipPersonal:\s*skipPersonal\.value/)
  assert.match(main, /resolveQrItemLookupKey/)
  assert.match(main, /qrFrequentInstanceIds/)
  assert.match(main, /仅暂停该微信本任务剩余项/)
  assert.match(main, /DEFAULT_QR_APPLY_TEXT/)
  assert.match(main, /reserveQrJoinDailyAttempt/)
})

test('task center shows executor and source for QR items', () => {
  const page = read('src/pages/TasksPage.vue')
  assert.match(page, /taskItemExecutorLabel/)
  assert.match(page, /taskItemSourceLabel/)
  assert.match(page, /执行微信/)
  assert.match(page, /来源微信/)
  assert.match(page, /sourceLabel/)
})

test('group start, count and exclusion rules filter members before task creation', () => {
  const page = read('src/pages/GroupsMembersPage.vue')
  assert.match(page, /function filterCandidates/)
  assert.match(page, /excludeText\.value\.split/)
  assert.match(page, /\.slice\(Math\.max\(startFrom\.value - 1/)
  assert.match(page, /Math\.max\(maxCount\.value/)
  const body = page.slice(page.indexOf('async function createAddFriendTask'), page.indexOf('async function collectLatestMembers'))
  assert.match(body, /const candidates = filterCandidates/)
  assert.match(body, /for \(const member of candidates\)/)
  assert.match(body, /status: 'PROFILE_PENDING'/)
  assert.doesNotMatch(body, /resolveFriendCredentials/)
})

test('scheduled broadcast options and per-row sender binding affect task creation', () => {
  const page = read('src/pages/BroadcastPage.vue')
  const main = read('electron/main.cjs')
  assert.match(page, /v-model="scheduledAt" type="datetime"/)
  assert.match(page, /selectedInstanceIds/)
  assert.match(page, /instanceId: String\(target\.sourceInstanceId\)/)
  assert.doesNotMatch(page, /allocationPool|accountWeights|allocMode/)
  assert.match(main, /task\?\.config\?\.scheduledAt/)
  assert.match(main, /waitForTaskTime\(taskId, scheduledAt\)/)
})

test('send retry uses configured count and delay but stops on uncertain results', () => {
  const page = read('src/pages/BroadcastPage.vue')
  const main = read('electron/main.cjs')
  assert.match(page, /retryMinutes: Number\(retryMinutes\.value\)/)
  assert.match(page, /skipSame: Boolean\(skipSame\.value\)/)
  // SEND_* 禁止可能已送达后的自动重发；仅 ADD_FRIEND 允许有限重试
  assert.match(main, /retryCount = item\.action_type === 'ADD_FRIEND' \? 1 : 0/)
  assert.match(main, /task\?\.config\?\.retryMinutes/)
  assert.match(main, /请求结果不确定，为避免重复发送已停止任务/)
  assert.match(main, /UNSAFE_RESUME/)
})

test('all task pacing uses the per-task fixed intervalMs', () => {
  const main = read('electron/main.cjs')
  const page = read('src/pages/TasksPage.vue')
  assert.match(main, /function resolveTaskPaceIntervalMs/)
  assert.match(main, /DEFAULT_TASK_PACE_INTERVAL_MS\s*=\s*1000/)
  assert.match(main, /hasOwnProperty\.call\(task\.config, 'intervalMs'\)/)
  assert.match(main, /task\?\.config\?\.intervalMs|task\.config\.intervalMs/)
  assert.match(main, /patchTaskConfig\(id, \{ intervalMs: intervalRaw \}\)/)
  assert.match(main, /itemIndex < taskItems\.length - 1/)
  assert.doesNotMatch(main, /settings\.intervalMin/)
  assert.doesNotMatch(main, /Math\.random\(\) \* \(max - min\)/)
  assert.match(page, /设置执行间隔/)
  assert.match(page, /confirmTask\(\{ id, intervalMs \}\)/)
  assert.match(page, /单位：毫秒/)
})
