const test = require('node:test')
const assert = require('node:assert/strict')
const { readFileSync } = require('node:fs')
const path = require('node:path')

test('task details open visibly and show only useful task and WeChat information', () => {
  const source = readFileSync(path.join(__dirname, '..', 'src', 'pages', 'TasksPage.vue'), 'utf8')

  assert.match(source, /async function viewTask/)
  assert.match(source, /taskItems\(id\)/)
  assert.match(source, />确认并开始<\/el-button>/)
  assert.match(source, /current\.statusCode === 'WAITING_CONFIRMATION'/)
  assert.match(source, />继续任务<\/el-button>/)
  assert.match(source, /resumeTask/)
  assert.match(source, /\['PAUSED', 'COOLING_DOWN'\]/)
  assert.match(source, /scrollIntoView\(\{ behavior: 'smooth', block: 'start' \}\)/)
  assert.match(source, /任务状态/)
  assert.match(source, /任务进度/)
  assert.match(source, /执行任务的微信/)
  assert.match(source, /微信号：/)
  assert.match(source, /instance\?\.alias \|\| instance\?\.accountWxid/)
  assert.match(source, /label="操作账号"/)
  assert.match(source, /taskItemTargetLabel/)
  assert.match(source, /未命名群聊/)
  assert.match(source, /群邀请（未解析到群名）/)
  assert.match(source, /revealTaskItemQrImage/)
  assert.match(source, /@row-dblclick/)
  assert.match(source, /listQrItems/)
  assert.match(source, /revealInFolder/)
  assert.doesNotMatch(source, /\? '二维码目标'/)
  assert.doesNotMatch(source, /prop="target_key"/)
  assert.doesNotMatch(source, /prop="plan"|label="进度"|<el-progress/)
  assert.doesNotMatch(source, /本地队列|按任务选择的微信/)
  assert.doesNotMatch(source, /执行策略|验证方式|重试规则|排除规则/)
})

test('task items resolve group and contact display names instead of roomId', () => {
  const storage = readFileSync(path.join(__dirname, '..', 'electron', 'storage.cjs'), 'utf8')
  assert.match(storage, /function getTaskItems/)
  assert.match(storage, /target_label/)
  assert.match(storage, /未命名群聊/)
  assert.match(storage, /群邀请（未解析到群名）/)
  assert.match(storage, /LEFT JOIN chatrooms room/)
  assert.match(storage, /LEFT JOIN contacts contact/)
  assert.match(storage, /targetLabel/)
  assert.doesNotMatch(storage, /二维码目标/)
  assert.match(storage, /preview\.roomName/)
})

test('task runner does not wait after its final item', () => {
  const source = readFileSync(path.join(__dirname, '..', 'electron', 'main.cjs'), 'utf8')
  const runTask = source.slice(source.indexOf('async function runTask'), source.indexOf('function createLocalTask'))

  assert.match(runTask, /itemIndex < taskItems\.length - 1/)
  assert.match(runTask, /doneItemStatuses/)
  assert.match(runTask, /REQUEST_SENT/)
  assert.match(runTask, /UNSAFE_RESUME/)
  assert.match(runTask, /if \(doneItemStatuses\.has\(String\(item\.status \|\| ''\)\)\) continue/)
  assert.match(runTask, /String\(item\.status \|\| ''\) === 'RUNNING'/)
  assert.match(runTask, /earlyContinueStatuses: \['QUEUED', 'RUNNING'\]/)
  assert.match(runTask, /leftover\.status === 'QUEUED'/)
  assert.match(source, /tasks:resume/)
  assert.match(source, /if \(runningTasks\.has\(id\)\) return true/)
})

test('task runner validates friend requests and sends the exact HAR friend fields', () => {
  const source = readFileSync(path.join(__dirname, '..', 'electron', 'main.cjs'), 'utf8')
  const runTask = source.slice(source.indexOf('async function runTask'), source.indexOf('function createLocalTask'))

  assert.match(runTask, /evaluateFriendAddResult\(response\.ok, raw\)/)
  assert.match(runTask, /DEFAULT_FRIEND_VERIFY_CONTENT/)
  assert.match(runTask, /verdict\.accepted \? 'REQUEST_SENT' : 'FAILED'/)
  assert.match(runTask, /'RESOLUTION_FAILED'/)
  assert.match(runTask, /'CREDENTIALS_READY'/)
  assert.match(runTask, /buildAddFriendRequest\(/)
  assert.match(runTask, /加好友成功：\$\{friendNick \|\| verdict\.reason \|\| '申请已提交'\}/)
  assert.match(runTask, /加好友失败：\$\{friendNick \|\| '好友'\}/)
  assert.match(runTask, /nickname: friendNick/)
  assert.match(runTask, /roomName: friendRoomName/)
  assert.match(runTask, /operation: 'ADD_FRIEND_RESULT'/)
  assert.match(source, /inviteUrl: joinUrl/)
  assert.doesNotMatch(runTask, /setTaskItemResult\(item\.id, 'SUBMITTED', raw, '好友申请已提交/)
})

test('kicked group cleanup runs as queued task items with per-room logs', () => {
  const source = readFileSync(path.join(__dirname, '..', 'electron', 'main.cjs'), 'utf8')
  const page = readFileSync(path.join(__dirname, '..', 'src', 'pages', 'TasksPage.vue'), 'utf8')
  const status = readFileSync(path.join(__dirname, '..', 'src', 'utils', 'status.ts'), 'utf8')
  const runTask = source.slice(source.indexOf('async function runTask'), source.indexOf('function createLocalTask'))
  const create = source.slice(source.indexOf('function createLocalTask'), source.indexOf('function portAvailable'))
  assert.match(create, /KICKED_GROUP_CLEANUP/)
  assert.match(runTask, /action_type === 'KICKED_GROUP_CLEANUP'/)
  assert.match(runTask, /cleanupOneKickedGroupRoom/)
  assert.match(runTask, /getKickedGroupCleanup/)
  assert.match(runTask, /formatKickCleanupMessage/)
  assert.match(runTask, /setTaskItemResult\(item\.id, result\.outcome, result, result\.message\)/)
  assert.match(status, /KICKED_GROUP_CLEANUP:\s*'清理被踢群'/)
  assert.match(page, /'被踢群'/)
  assert.match(page, /typeCode === 'KICKED_GROUP_CLEANUP'/)
  const storage = readFileSync(path.join(__dirname, '..', 'electron', 'storage.cjs'), 'utf8')
  assert.match(storage, /function getKickedGroupCleanup/)
  assert.match(storage, /function listActiveKickedCleanupTargets/)
  assert.match(storage, /action_type = 'KICKED_GROUP_CLEANUP'/)
})
