const test = require('node:test')
const assert = require('node:assert/strict')
const { readFileSync } = require('node:fs')
const path = require('node:path')

const read = (file) => readFileSync(path.join(__dirname, '..', file), 'utf8')

test('QR account limit and cooldown are passed into execution', () => {
  const page = read('src/pages/QrTasksPage.vue')
  const main = read('electron/main.cjs')
  assert.match(page, /capacity = availableInstances\.length \* limitPerAccount\.value/)
  assert.match(page, /limitPerAccount:\s*limitPerAccount\.value/)
  assert.match(page, /coolMinutes:\s*coolMinutes\.value/)
  assert.match(page, /applyText:\s*applyText\.value/)
  assert.match(page, /你好，想加入群聊/)
  assert.match(page, /需群主确认的群必须填写/)
  assert.match(page, /skipPersonal:\s*skipPersonal\.value/)
  assert.match(main, /DEFAULT_QR_APPLY_TEXT/)
  assert.match(main, /requestSent/)
  assert.match(main, /task\?\.config\?\.coolMinutes/)
  assert.match(main, /applyQrOptions\(record, task, item, decodedText, taskId\)/)
  assert.match(main, /reserveQrJoinDailyAttempt/)
})

test('group start, count and exclusion rules filter members before task creation', () => {
  const page = read('src/pages/GroupsMembersPage.vue')
  assert.match(page, /function filterCandidates/)
  assert.match(page, /excludeText\.value\.split/)
  assert.match(page, /\.slice\(Math\.max\(startFrom\.value - 1/)
  assert.match(page, /Math\.max\(maxCount\.value/)
  const body = page.slice(page.indexOf('async function createAddFriendTask'), page.indexOf('async function collectLatestMembers'))
  assert.match(body, /const candidates = filterCandidates/)
  assert.match(body, /for \(const member of candidates\)/)
  assert.match(body, /status: 'PROFILE_PENDING'/)
  assert.doesNotMatch(body, /resolveFriendCredentials/)
})

test('scheduled broadcast options and per-row sender binding affect task creation', () => {
  const page = read('src/pages/BroadcastPage.vue')
  const main = read('electron/main.cjs')
  assert.match(page, /v-model="scheduledAt" type="datetime"/)
  assert.match(page, /selectedInstanceIds/)
  assert.match(page, /instanceId: String\(target\.sourceInstanceId\)/)
  assert.doesNotMatch(page, /allocationPool|accountWeights|allocMode/)
  assert.match(main, /task\?\.config\?\.scheduledAt/)
  assert.match(main, /waitForTaskTime\(taskId, scheduledAt\)/)
})

test('send retry uses configured count and delay but stops on uncertain results', () => {
  const page = read('src/pages/BroadcastPage.vue')
  const main = read('electron/main.cjs')
  assert.match(page, /retryMinutes: Number\(retryMinutes\.value\)/)
  assert.match(page, /skipSame: Boolean\(skipSame\.value\)/)
  assert.match(main, /task\?\.config\?\.autoRetry/)
  assert.match(main, /task\.config\.retryTimes/)
  assert.match(main, /task\?\.config\?\.retryMinutes/)
  assert.match(main, /请求结果不确定，为避免重复发送已停止任务/)
})

test('all task pacing uses only the global random interval', () => {
  const main = read('electron/main.cjs')
  assert.match(main, /const min = Math\.max\(Number\(settings\.intervalMin\)/)
  assert.match(main, /itemIndex < taskItems\.length - 1/)
  assert.doesNotMatch(main, /task\?\.config\?\.intervalMin/)
})
