const test = require('node:test')
const assert = require('node:assert/strict')
const { existsSync, readFileSync } = require('node:fs')
const path = require('node:path')

test('system tray provides the four requested menu entries', () => {
  const root = path.join(__dirname, '..')
  const source = readFileSync(path.join(root, 'electron', 'main.cjs'), 'utf8')

  assert.equal(existsSync(path.join(root, 'electron', 'tray-icon.png')), true)
  assert.equal(existsSync(path.join(root, 'electron', 'app-icon.ico')), true)
  assert.match(source, /new Tray/)
  assert.match(source, /app-icon\.ico/)
  assert.match(source, /resolveAppIconPath/)
  assert.match(source, /icon: appIconPath|icon: resolveAppIconPath\(\)/)
  assert.match(source, /win\.setIcon\(appIconPath\)/)
  assert.match(source, /label: '显示主界面'/)
  assert.match(source, /activateMainWindow/)
  assert.match(source, /label: '重启软件'/)
  assert.match(source, /label: '退出软件'/)
  assert.match(source, /function restartApp/)
  assert.match(source, /releaseSingleInstanceLock/)
  assert.match(source, /PORTABLE_EXECUTABLE_FILE/)
  assert.match(source, /app\.relaunch\(/)
  assert.match(source, /app\.exit\(0\)/)
  assert.match(source, /click: \(\) => restartApp\(\)/)
  // Tray itself must not pin the window; brief alwaysOnTop is allowed only in showMainWindow activate path
  assert.doesNotMatch(source, /function createTray[\s\S]*?setAlwaysOnTop/)
})
