const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const root = path.resolve(__dirname, '..')

test('webrtc publisher files are packaged under electron/', () => {
  for (const rel of [
    'electron/webrtc-desktop.cjs',
    'electron/webrtc-publisher.html',
    'electron/webrtc-publisher-preload.cjs',
    'electron/vendor/livekit-client.umd.js',
  ]) {
    assert.equal(fs.existsSync(path.join(root, rel)), true, rel)
  }
})

test('livekit publisher guards: reuse room, timeout cleanup, reconnect soft-state', () => {
  const html = fs.readFileSync(path.join(root, 'electron/webrtc-publisher.html'), 'utf8')
  const mod = fs.readFileSync(path.join(root, 'electron/webrtc-desktop.cjs'), 'utf8')
  const agent = fs.readFileSync(path.join(root, 'electron/remote-agent.cjs'), 'utf8')
  assert.match(html, /livekit-client\.umd\.js/)
  assert.match(html, /LK\.Room/)
  assert.match(html, /getDisplayMedia_timeout/)
  assert.match(html, /timedOut/)
  assert.match(html, /25000/)
  assert.match(html, /stream\.getTracks\(\)\.forEach/)
  assert.match(html, /reused: true/)
  assert.match(html, /publishedTrack\.readyState === 'live'/)
  assert.match(html, /signalReconnecting/)
  assert.match(html, /maxBitrate: 900_000|maxBitrate: 900000/)
  assert.match(html, /contentHint = 'detail'/)
  assert.match(html, /cmdChain/)
  assert.match(html, /dynacast: false/)
  assert.match(html, /adaptiveStream: false/)
  assert.match(html, /room !== nextRoom/)
  assert.match(html, /keepStream/)
  assert.match(html, /roomEpoch/)
  assert.match(html, /scheduleAutoReconnect/)
  assert.match(html, /reconnectAttempt/)
  assert.match(html, /Math\.pow\(1\.7/)
  assert.match(html, /intentionalStop/)
  assert.match(html, /skipUnpublish/)
  assert.match(html, /connectionState: 'capturing'/)
  assert.match(html, /captureTimeout/)
  assert.match(mod, /soft = /)
  assert.match(mod, /getDisplayMedia_timeout/)
  assert.match(mod, /CAPTURE_FAIL_RECYCLE_AT/)
  assert.match(mod, /recyclePublisherWindow/)
  assert.match(mod, /scheduleJpegResume/)
  assert.match(mod, /isWebRtcMediaConnected/)
  assert.match(mod, /isWebRtcDesktopActive/)
  assert.match(mod, /isWebRtcCaptureBusy/)
  assert.match(mod, /isWebRtcStarting/)
  assert.match(mod, /markWebRtcStarting/)
  assert.match(mod, /STARTING_GUARD_MS/)
  assert.match(mod, /captureBusy/)
  assert.match(mod, /queuedStart/)
  assert.match(mod, /clearStopWaitTimer/)
  assert.match(mod, /activeRoomName/)
  assert.match(mod, /wantForce/)
  assert.match(mod, /opts\.forceRestart \|\| opts\.kick \|\| opts\.force/)
  assert.match(mod, /captureBusy = false\s*\n\s*markWebRtcStarting\(false\)\s*\n\s*return \{ ok: true, reused: true \}/)
  assert.match(mod, /scheduleJpegResume\(8000\)/)
  assert.match(mod, /重连期间可能再次 getDisplayMedia/)
  assert.match(mod, /mediaConnected = false\s*\n\s*captureBusy = false\s*\n\s*markWebRtcStarting\(false\)/)
  assert.match(mod, /DUPLICATE_IDENTITY/)
  assert.match(mod, /reconnecting/)
  assert.match(mod, /destroy\(\)/)
  assert.match(mod, /jpegResumeTimer|clearJpegResumeTimer/)
  assert.match(agent, /isWebRtcMediaConnected\(\)/)
  assert.match(agent, /isWebRtcDesktopActive\(\)/)
  assert.match(agent, /isWebRtcCaptureBusy\(\)/)
  assert.match(agent, /isWebRtcStarting\(\)/)
  assert.match(agent, /markWebRtcStarting\(true\)/)
  assert.match(agent, /agentMsgChain/)
  assert.match(agent, /stopWebRtcDesktop\(\)/)
  assert.match(agent, /jpeg_snapshot/)
  assert.match(agent, /!state\.watching/)
  assert.match(agent, /forceRestart: !isWebRtcMediaConnected\(\)/)
  assert.match(agent, /handleControlPayload\(message\.payload/)
  assert.match(agent, /JPEG_SNAPSHOT_INTERVAL_MS/)
  assert.doesNotMatch(agent, /JPEG_SNAPSHOT_INTERVAL_MS \* 6/)
})

test('screen wall slows webrtc hard-kick to protect getDisplayMedia recovery', () => {
  const portal = fs.readFileSync(path.join(root, '..', 'server/wxqk/deploy_rd_portal_888.py'), 'utf8')
  assert.match(portal, /START_COOLDOWN_MS = 45000/)
  assert.match(portal, /kickGap = src\.preferWebRtc \? 90000/)
  assert.match(portal, /tryingAge < WEBRTC_CONNECT_TIMEOUT_MS/)
  assert.match(portal, /isLivekitVideoFresh\(c\)/)
  assert.match(portal, /假死最后一帧必须允许/)
  assert.match(portal, /> 90000/)
})

test('server demoted force still soft-starts; token rotate rate-limited', () => {
  const py = fs.readFileSync(path.join(root, '..', 'server/wxqk/server.py'), 'utf8')
  assert.match(py, /demoted = False/)
  assert.match(py, /demoted = True/)
  assert.match(py, /if demoted:/)
  assert.match(py, /since_soft < 25\.0/)
  assert.match(py, /_DESKTOP_FORCE_RESTART_MIN_SEC = 90/)
  assert.match(py, /_DESKTOP_LIVEKIT_START_COALESCE_SEC = 120/)
})

test('server livekit session helper is present for desktop transport', () => {
  const py = fs.readFileSync(path.join(root, '..', 'server/wxqk/livekit_session.py'), 'utf8')
  const sess = fs.readFileSync(path.join(root, '..', 'server/wxqk/webrtc_session.py'), 'utf8')
  assert.match(py, /def mint_token|def issue_token|livekit/)
  assert.match(sess, /livekit/)
  assert.match(sess, /def create_session|def create/)
})
