const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('path')
const { isWeixinExe, compareVersion, commonCandidatePaths } = require('../electron/weixin-detect.cjs')

test('weixin detect helpers normalize candidates and versions', () => {
  assert.equal(isWeixinExe(''), false)
  assert.equal(compareVersion('4.1.8.27', '4.1.7.0') > 0, true)
  assert.equal(compareVersion('4.0.0', '4.0.0'), 0)
  assert.ok(commonCandidatePaths().some((item) => /Weixin\.exe$/i.test(item)))
})

test('startup auto-detects weixin path and settings expose redetect', () => {
  const root = path.join(__dirname, '..')
  const main = fs.readFileSync(path.join(root, 'electron', 'main.cjs'), 'utf8')
  const page = fs.readFileSync(path.join(root, 'src', 'pages', 'SettingsLogsPage.vue'), 'utf8')
  const preload = fs.readFileSync(path.join(root, 'electron', 'preload.cjs'), 'utf8')
  const detect = fs.readFileSync(path.join(root, 'electron', 'weixin-detect.cjs'), 'utf8')
  assert.match(detect, /function detectPreferredWeixin/)
  assert.match(detect, /Weixin\.exe/)
  assert.match(detect, /versionCache/)
  assert.match(main, /ensureWeixinPathConfigured/)
  assert.match(main, /禁止为读版本再拉起 PowerShell/)
  assert.match(main, /setImmediate\(\(\) => \{[\s\S]*?ensureWeixinPathConfigured/)
  assert.match(main, /void softwareAuth\.session\(\)/)
  assert.match(main, /weixin:detect/)
  assert.match(main, /detectPreferredWeixin/)
  assert.match(preload, /detectWeixinInstall/)
  assert.match(page, /重新检测/)
  assert.match(page, /手动选择/)
  assert.match(page, /detectWeixinInstall/)
  assert.doesNotMatch(page, /恢复默认.*E:\\\\weixin/)
})
